[package]
name = "nft-factory"
version = "1.1.0"
authors = ["hthuang <hht2015ily@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "3.1.0"
near-contract-standards = "3.1.1"
